// Mock data for testing when Polymarket API is unreachable
// Based on real market data from https://polymarket.com/event/next-james-bond-actor-635

export const MOCK_EVENTS = [
  {
    id: 'next-james-bond-actor-635',
    slug: 'next-james-bond-actor-635',
    title: 'Next James Bond actor?',
    description: 'This market will resolve to "Yes" if the above actor is officially announced as the next James Bond actor by June 30, 2026.',
    startDate: '2024-01-01T00:00:00Z',
    endDate: '2026-06-30T00:00:00Z',
    volume: 493924,
    liquidity: 183825,
    active: true,
    closed: false,
    negRisk: true,
    // 12 mutually exclusive outcomes - exactly one actor will be chosen
    markets: [
      {
        id: 'bond-no-choice',
        question: 'No Bond chosen',
        groupItemTitle: 'No Bond chosen',
        outcomePrices: JSON.stringify([0.45, 0.55]),
        clobTokenIds: JSON.stringify(['mock-token-bond-no-yes', 'mock-token-bond-no-no']),
        volume: 183825,
        active: true,
      },
      {
        id: 'bond-callum-turner',
        question: 'Callum Turner',
        groupItemTitle: 'Callum Turner',
        outcomePrices: JSON.stringify([0.37, 0.63]),
        clobTokenIds: JSON.stringify(['mock-token-callum-yes', 'mock-token-callum-no']),
        volume: 38789,
        active: true,
      },
      {
        id: 'bond-aaron-taylor',
        question: 'Aaron Taylor-Johnson',
        groupItemTitle: 'Aaron Taylor-Johnson',
        outcomePrices: JSON.stringify([0.124, 0.876]),
        clobTokenIds: JSON.stringify(['mock-token-aaron-yes', 'mock-token-aaron-no']),
        volume: 31558,
        active: true,
      },
      {
        id: 'bond-jacob-elordi',
        question: 'Jacob Elordi',
        groupItemTitle: 'Jacob Elordi',
        outcomePrices: JSON.stringify([0.127, 0.873]),
        clobTokenIds: JSON.stringify(['mock-token-jacob-yes', 'mock-token-jacob-no']),
        volume: 32730,
        active: true,
      },
      {
        id: 'bond-henry-cavill',
        question: 'Henry Cavill',
        groupItemTitle: 'Henry Cavill',
        outcomePrices: JSON.stringify([0.031, 0.969]),
        clobTokenIds: JSON.stringify(['mock-token-henry-yes', 'mock-token-henry-no']),
        volume: 22153,
        active: true,
      },
      {
        id: 'bond-tom-holland',
        question: 'Tom Holland',
        groupItemTitle: 'Tom Holland',
        outcomePrices: JSON.stringify([0.008, 0.992]),
        clobTokenIds: JSON.stringify(['mock-token-tom-h-yes', 'mock-token-tom-h-no']),
        volume: 24776,
        active: true,
      },
      {
        id: 'bond-jack-lowdon',
        question: 'Jack Lowdon',
        groupItemTitle: 'Jack Lowdon',
        outcomePrices: JSON.stringify([0.005, 0.995]),
        clobTokenIds: JSON.stringify(['mock-token-jack-yes', 'mock-token-jack-no']),
        volume: 24348,
        active: true,
      },
      {
        id: 'bond-james-norton',
        question: 'James Norton',
        groupItemTitle: 'James Norton',
        outcomePrices: JSON.stringify([0.004, 0.996]),
        clobTokenIds: JSON.stringify(['mock-token-james-yes', 'mock-token-james-no']),
        volume: 37378,
        active: true,
      },
      {
        id: 'bond-tom-hardy',
        question: 'Tom Hardy',
        groupItemTitle: 'Tom Hardy',
        outcomePrices: JSON.stringify([0.004, 0.996]),
        clobTokenIds: JSON.stringify(['mock-token-tom-hardy-yes', 'mock-token-tom-hardy-no']),
        volume: 12614,
        active: true,
      },
      {
        id: 'bond-harris-dickinson',
        question: 'Harris Dickinson',
        groupItemTitle: 'Harris Dickinson',
        outcomePrices: JSON.stringify([0.004, 0.996]),
        clobTokenIds: JSON.stringify(['mock-token-harris-yes', 'mock-token-harris-no']),
        volume: 29265,
        active: true,
      },
      {
        id: 'bond-paul-mescal',
        question: 'Paul Mescal',
        groupItemTitle: 'Paul Mescal',
        outcomePrices: JSON.stringify([0.002, 0.998]),
        clobTokenIds: JSON.stringify(['mock-token-paul-yes', 'mock-token-paul-no']),
        volume: 28266,
        active: true,
      },
      {
        id: 'bond-pierce-brosnan',
        question: 'Pierce Brosnan',
        groupItemTitle: 'Pierce Brosnan',
        outcomePrices: JSON.stringify([0.002, 0.998]),
        clobTokenIds: JSON.stringify(['mock-token-pierce-yes', 'mock-token-pierce-no']),
        volume: 28222,
        active: true,
      },
    ],
  },
  // Example of an INVALID market (cumulative thresholds - should be filtered out)
  {
    id: 'megaeth-fdv-mock',
    slug: 'megaeth-fdv-mock',
    title: 'MegaETH market cap (FDV)',
    description: 'Markets for MegaETH fully diluted valuation thresholds',
    startDate: '2024-01-01T00:00:00Z',
    endDate: '2026-12-31T00:00:00Z',
    volume: 50000,
    liquidity: 10000,
    active: true,
    closed: false,
    negRisk: false,
    // CUMULATIVE THRESHOLDS - NOT mutually exclusive!
    markets: [
      {
        id: 'megaeth-1b',
        question: '>$1B',
        groupItemTitle: '>$1B',
        outcomePrices: JSON.stringify([0.70, 0.30]),
        clobTokenIds: JSON.stringify(['mock-mega-1b-yes', 'mock-mega-1b-no']),
        volume: 15000,
        active: true,
      },
      {
        id: 'megaeth-2b',
        question: '>$2B',
        groupItemTitle: '>$2B',
        outcomePrices: JSON.stringify([0.50, 0.50]),
        clobTokenIds: JSON.stringify(['mock-mega-2b-yes', 'mock-mega-2b-no']),
        volume: 12000,
        active: true,
      },
      {
        id: 'megaeth-5b',
        question: '>$5B',
        groupItemTitle: '>$5B',
        outcomePrices: JSON.stringify([0.30, 0.70]),
        clobTokenIds: JSON.stringify(['mock-mega-5b-yes', 'mock-mega-5b-no']),
        volume: 13000,
        active: true,
      },
      {
        id: 'megaeth-10b',
        question: '>$10B',
        groupItemTitle: '>$10B',
        outcomePrices: JSON.stringify([0.15, 0.85]),
        clobTokenIds: JSON.stringify(['mock-mega-10b-yes', 'mock-mega-10b-no']),
        volume: 10000,
        active: true,
      },
    ],
  },
  // Example of temporal deadline market (should be filtered)
  {
    id: 'btc-100k-dates-mock',
    slug: 'btc-100k-dates-mock',
    title: 'When will BTC hit $100k?',
    description: 'Markets for when Bitcoin will reach $100,000',
    startDate: '2024-01-01T00:00:00Z',
    endDate: '2026-12-31T00:00:00Z',
    volume: 100000,
    liquidity: 25000,
    active: true,
    closed: false,
    negRisk: false,
    // Different time windows - NOT mutually exclusive
    markets: [
      {
        id: 'btc-q1-2026',
        question: 'BTC to $100k in Q1 2026?',
        groupItemTitle: 'Q1 2026',
        outcomePrices: JSON.stringify([0.20, 0.80]),
        clobTokenIds: JSON.stringify(['mock-btc-q1-yes', 'mock-btc-q1-no']),
        volume: 25000,
        active: true,
      },
      {
        id: 'btc-q2-2026',
        question: 'BTC to $100k in Q2 2026?',
        groupItemTitle: 'Q2 2026',
        outcomePrices: JSON.stringify([0.35, 0.65]),
        clobTokenIds: JSON.stringify(['mock-btc-q2-yes', 'mock-btc-q2-no']),
        volume: 30000,
        active: true,
      },
      {
        id: 'btc-q3-2026',
        question: 'BTC to $100k in Q3 2026?',
        groupItemTitle: 'Q3 2026',
        outcomePrices: JSON.stringify([0.45, 0.55]),
        clobTokenIds: JSON.stringify(['mock-btc-q3-yes', 'mock-btc-q3-no']),
        volume: 25000,
        active: true,
      },
      {
        id: 'btc-q4-2026',
        question: 'BTC to $100k in Q4 2026?',
        groupItemTitle: 'Q4 2026',
        outcomePrices: JSON.stringify([0.50, 0.50]),
        clobTokenIds: JSON.stringify(['mock-btc-q4-yes', 'mock-btc-q4-no']),
        volume: 20000,
        active: true,
      },
    ],
  },
  // Another valid winner-take-all market
  {
    id: 'best-picture-2026-mock',
    slug: 'best-picture-2026-mock',
    title: 'Best Picture at 2026 Oscars?',
    description: 'Which film will win Best Picture at the 98th Academy Awards?',
    startDate: '2024-01-01T00:00:00Z',
    endDate: '2026-03-15T00:00:00Z',
    volume: 250000,
    liquidity: 50000,
    active: true,
    closed: false,
    negRisk: true,
    // Mutually exclusive - only one film wins
    markets: [
      {
        id: 'oscar-anora',
        question: 'Anora',
        groupItemTitle: 'Anora',
        outcomePrices: JSON.stringify([0.35, 0.65]),
        clobTokenIds: JSON.stringify(['mock-oscar-anora-yes', 'mock-oscar-anora-no']),
        volume: 80000,
        active: true,
      },
      {
        id: 'oscar-conclave',
        question: 'Conclave',
        groupItemTitle: 'Conclave',
        outcomePrices: JSON.stringify([0.28, 0.72]),
        clobTokenIds: JSON.stringify(['mock-oscar-conclave-yes', 'mock-oscar-conclave-no']),
        volume: 60000,
        active: true,
      },
      {
        id: 'oscar-brutalist',
        question: 'The Brutalist',
        groupItemTitle: 'The Brutalist',
        outcomePrices: JSON.stringify([0.22, 0.78]),
        clobTokenIds: JSON.stringify(['mock-oscar-brutalist-yes', 'mock-oscar-brutalist-no']),
        volume: 50000,
        active: true,
      },
      {
        id: 'oscar-emilia',
        question: 'Emilia Pérez',
        groupItemTitle: 'Emilia Pérez',
        outcomePrices: JSON.stringify([0.10, 0.90]),
        clobTokenIds: JSON.stringify(['mock-oscar-emilia-yes', 'mock-oscar-emilia-no']),
        volume: 30000,
        active: true,
      },
      {
        id: 'oscar-other',
        question: 'Other',
        groupItemTitle: 'Other',
        outcomePrices: JSON.stringify([0.08, 0.92]),
        clobTokenIds: JSON.stringify(['mock-oscar-other-yes', 'mock-oscar-other-no']),
        volume: 30000,
        active: true,
      },
    ],
  },
];

// Flag to control mock mode
// Set to true when Polymarket API is unreachable (VM proxy blocks it)
// Set to false when running on a machine with direct internet access
export const USE_MOCK_DATA = false;  // Will auto-fallback if network fails anyway

export function getMockEvents() {
  console.log('[MOCK] Returning mock event data for testing');
  return MOCK_EVENTS;
}
